pfe/pfe/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('translation.urls')),
]
handler404 = 'translation.views.error_404'

pfe/translation/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'translation'
urlpatterns = [
    path('', views.index,name='index'),
    path('start-now/', views.play_video,name='startnow'),
    path('creat-script/', views.creation_script,name='creat-script'),
    path('generate-script/', views.generer_script,name='generate-script'),
    path('watch/', views.watch,name='watch'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pfe/translation/models.py
from django.db import models

# Create your models here.

pfe/translation/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
import requests,os,re,pytube,json,mimetypes,random,string,subprocess,glob
from django.views.decorators.csrf import csrf_exempt
from requests.adapters import HTTPAdapter
from django.core.mail import send_mail

MEDIA_PATH=os.path.abspath('translation/media')

def convert(srt,video,random_name):
    subprocess.check_output(['ffmpeg','-hide_banner','-i',srt,srt.split('.')[0]+'.ass'], cwd=MEDIA_PATH)
    subprocess.check_output(['ffmpeg','-hide_banner','-threads','auto','-y', '-i',video, '-vf','ass='+srt.split('.')[0]+'.ass','-preset','ultrafast',random_name+'.mp4'],cwd=MEDIA_PATH)
    for file_name in glob.glob(MEDIA_PATH+'/'+srt.split('.')[0]+'.*'):
        os.remove(file_name)

def watch(request):
    if 'video' in request.COOKIES:
        return render(request,'translation/watch.html',{"video":request.COOKIES['video']})
    else:
        return render(request,'translation/error.html')

@csrf_exempt
def index(request):
    if request.method =="POST":
        user_name = request.POST['user_name']
        user_email = request.POST['user_email']
        user_description = request.POST['des']
        send_mail(
            "Email from "+user_name,
            user_description,
            user_email,
            ['test-tosend@mail.com'],
        )  
        return render(request,'translation/index.html', {"user_name":user_name})
    response =  render(request,'translation/index.html', {'nbar': 'home'})
    response.delete_cookie('video')
    return response

def error_404(request, exception):
    return render(request,'translation/404.html', status = 404)

@csrf_exempt
def creation_script(request):
    if 'video' in request.COOKIES and request.method == "GET":
        return render(request,'translation/creation_scripte.html',{"video":request.COOKIES['video']})
    
    elif 'video' in request.COOKIES and request.method == "POST":
        if request.POST.get('srt') != '':
            random_name = ''.join(random.choice(string.ascii_lowercase) for i in range(5))
            srt_name=request.COOKIES['video'].split('.')[0]+'.vtt'
            with open('{}/{}'.format(MEDIA_PATH,srt_name),"w")as f:
                f.write("WEBVTT\n\r"+request.POST.get('srt').replace('\r\n','\n'))
            reponse= HttpResponse(json.dumps({'message': 'ok',}),content_type="application/json")
            convert(srt_name,request.COOKIES['video'],random_name)
            reponse.set_cookie("video",random_name+'.mp4')
            return reponse
        else:
            return HttpResponse(json.dumps({'message': 'not valid'}),content_type="application/json")
    
    else:
        return render(request,'translation/error.html')
    

@csrf_exempt
def generer_script(request):
    if 'video' in request.COOKIES:
        random_name = ''.join(random.choice(string.ascii_lowercase) for i in range(5))
        srt_name = request.COOKIES['video'].split('.')[0]+'.vtt'
        if request.method =="POST":
            sub_file = request.FILES['mySub']
            if str(sub_file).split('.')[-1].lower()=="srt":
                with open('{}/{}'.format(MEDIA_PATH,srt_name),"w")as f:
                    f.write("WEBVTT\n"+str(sub_file.read().decode()).replace(',','.'))
            else:
                fs = FileSystemStorage()
                fs.save(srt_name,sub_file)
            convert(srt_name,request.COOKIES['video'],random_name)
            reponse= HttpResponse(json.dumps({'message': 'ok',}),content_type="application/json")
            reponse.set_cookie("video",random_name+'.mp4')
            return reponse
            
        return render(request,'translation/generer_script.html',{"video":request.COOKIES['video']})
    else:
        return render(request,'translation/error.html')
         
@csrf_exempt
def play_video(request):
    if request.method == 'POST':
        url = request.POST.get('link')
        if "myVideo" in request.FILES and url =="":
            video_upload=''.join(random.choice(string.ascii_lowercase) for i in range(5))+'.'+str(request.FILES['myVideo']).split('.')[-1]
            video = request.FILES['myVideo']
            fs = FileSystemStorage()
            fs.save(video_upload,video)
            reponse= HttpResponse(json.dumps({'message': 'ok',}),content_type="application/json")
            reponse.set_cookie("video",video_upload)
            return reponse
        elif url != "" and url != None and not "myVideo" in request.FILES:
            try:
                if re.match(r'^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$',url):
                    video = pytube.YouTube(url)
                    video_name=''.join(random.choice(string.ascii_lowercase) for i in range(5))
                    video.streams.get_highest_resolution().download(MEDIA_PATH,filename=video_name)
                    response = HttpResponse(json.dumps({'message': 'ok',}),content_type="application/json")
                    response.set_cookie('video',video_name+'.mp4')
                    return response
                elif mimetypes.MimeTypes().guess_type(url)[0].startswith("video"):
                    video_extension=''.join(random.choice(string.ascii_lowercase) for i in range(5))+'.'+url.split('/')[-1].split('.')[-1]
                    with requests.Session() as s:
                        s.mount('https://', HTTPAdapter(max_retries=20))
                        r = s.get(url,stream=True)
                        with open('{}/{}'.format(MEDIA_PATH,video_extension), 'wb') as f:
                            for chunk in r.iter_content(chunk_size=1024):
                                if chunk:
                                    f.write(chunk)
                        reponse = HttpResponse(json.dumps({'message': 'ok'}),content_type="application/json")
                        reponse.set_cookie("video",video_extension)
                        return reponse
            except Exception:
                return HttpResponse(json.dumps({'message': 'not valid'}),content_type="application/json")
        
        elif url =='' and not "myVideo" in request.FILES:
            return HttpResponse(json.dumps({'message': 'empty'}),content_type="application/json")
        elif request.FILES['myVideo'] !="" and request.POST.get('link') !="":
            return HttpResponse(json.dumps({'message': 'url and files'}),content_type="application/json")
         
    reponse =  render(request,'translation/blog-single.html')
    reponse.delete_cookie('video')
    return reponse

pfe/translation/templates/translation/creation_scripte.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Rex : Create script</title>

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/icon" href="{% static 'translation/assets/images/favicon.ico' %}" />
  <!-- Font Awesome -->
  <link href="{% static 'translation/assets/css/font-awesome.css' %}" rel="stylesheet">
  <!-- Sweet Alerte -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css" rel="stylesheet">
  <!-- Bootstrap -->
  <link href="{% static 'translation/assets/css/bootstrap.css' %}" rel="stylesheet">
  <!-- Slick slider -->
  <link rel="stylesheet" type="text/css" href="{% static 'translation/assets/css/slick.css' %}" />
  <!-- Fancybox slider -->
  <link rel="stylesheet" href="{% static 'translation/assets/css/jquery.fancybox.css' %}" type="text/css"
    media="screen" />
  <!-- Animate css -->
  <link rel="stylesheet" type="text/css" href="{% static 'translation/assets/css/animate.css' %}" />
  <!-- Theme color -->
  <link id="switcher" href="{% static 'translation/assets/css/theme-color/default.css' %}" rel="stylesheet">

  <!-- Main Style -->
  <link href="{% static 'translation/style.css' %}" rel="stylesheet">



  <!-- Fonts -->
  <!-- Open Sans for body font -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <!-- Raleway for Title -->
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <!-- Pacifico for 404 page   -->
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
  <!-- BEGAIN PRELOADER -->
  <div id="preloader">
    <div class="loader">&nbsp;</div>
  </div>
  <!-- END PRELOADER -->

  <!-- SCROLL TOP BUTTON -->
  <a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->

  <!-- Start menu section -->
  <section id="menu-area">
    <nav class="navbar navbar-default main-navbar" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->
          <a class="navbar-brand logo" href="{% url 'translation:index' %}"><img
              src="{% static 'translation/assets/images/logo.jpg' %}" alt="logo"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav main-nav menu-scroll">
            <li><a href="">Home</a></li>
            <li class="active"><a href="">Create Script </a></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
        <div class="search-area">
          <form action="">
            <input id="search" name="search" type="text" placeholder="What're you looking for ?">
            <input id="search_submit" value="Rechercher" type="submit">
          </form>
        </div>
      </div>
    </nav>
  </section>
  <!-- End menu section -->
  <!-- Start blog banner section -->
  <section id="blog-banner">
    <img src="{% static 'translation/assets/images/blog-banner.jpg' %}" alt="img">
    <div class="blog-overlay">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="blog-banner-area">
              <h2>Let's create your script </h2>
              <ol class="breadcrumb">
                <li><a href="{% url 'translation:index' %}">Home</a></li>
                <li class="active">Create scripte</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End blog banner section -->

  <!-- Start blog section -->
  <section id="blog">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="blog-area">
            <div class="row">
              <div class="col-lg-6 col-md-7 col-sm-12">
                <div class="blog-left blog-details">
                  <!-- Start single blog post -->
                  <article class="single-from-blog">

                    <div class="single-widget">
                      <h2>Creation section</h2><br>



                      <div class="single-widget" style="width: 500px; height: 400px; ">
                        <h2>Create your own script</h2>

                        <form method="POST" action="" id="frm_srt">
                          <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="15"
                            placeholder="Write something here..." name="srt"></textarea>
                      </div>

                      <center>
                        <div>
                        <p id="myElem" class="label label-success" style="display:none">Subtitles file created with success , Click on watch to continue.... </p>
                        <p id="error" class="label label-info " style="display:none">Sorry we couldn't create your file , textarea should not be empty</p>
                      </div>
                    </center>

                      <button style="margin-left: 2.4rem;" class="button button-default col-sm-11" data-text="Create"
                        name="Create"><span>Create </span></button>

                    </div>
                    </form>
                   
                <div id="watch_but" hidden>
                    <button style="margin-left: 2.4rem;" class="button button-default col-sm-11" data-text="Watch the result >>"
                      name="watch" onClick="parent.location='/watch/'" ><span>watch </span></button>
                    </div>
                  </article>
                  <!-- End single blog post -->
                </div>

              </div>

              <div class="col-lg-6 col-md-6 col-sm-12">
                <aside class="blog-right">
                  <!-- Start Sidebar Single widget -->

                  <div class="single-widget">
                    <h2>How to create an SRT file </h2>
                    <p>This image shows an ideal example of how to write your own <strong>SRT</strong> file </p><br>
                    <img src="{% static 'translation/assets/images/example_srt.jpg' %}" class="img-fluid popup"
                      style="margin-left: 4rem;" width="400" height="200">

                    <center><label for="" style="color:mediumaquamarine ;">Click on the image to enlarge</label>
                    </center>
                    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                      aria-labelledby="myLargeModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                          <img id="popup-img" src="" alt="image">
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="single-widget">

                    <h2>video Preview</h2>
                    <video controls="" id="media" controls width="500" height="300">
                      <source src="/media/{{video}}">
                    </video>

                  </div>

                  <!-- End Sidebar Single widget -->


                </aside>
              </div>
            </div>
          </div>
        </div>
      </div>
  </section>
  <!-- End blog section -->

  <!-- Start Footer -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer-top-area">
              <a class="footer-logo" href="#"><img src="{% static 'translation/assets/images/logo.jpg' %}"
                  alt="Logo"></a>
              <div class="footer-social">
                <a class="facebook" href="#"><span class="fa fa-facebook"></span></a>
                <a class="twitter" href="#"><span class="fa fa-twitter"></span></a>
                <a class="google-plus" href="#"><span class="fa fa-google-plus"></span></a>
                <a class="youtube" href="#"><span class="fa fa-youtube"></span></a>
                <a class="linkedin" href="#"><span class="fa fa-linkedin"></span></a>
                <a class="dribbble" href="#"><span class="fa fa-dribbble"></span></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </footer>
  <!-- End Footer -->
  <!-- jQuery library -->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <!-- Bootstrap -->

  <script src="{% static 'translation/assets/js/bootstrap.js' %}"></script>
  <!-- Slick Slider -->
  <script type="text/javascript" src="{% static 'translation/assets/js/slick.js' %}"></script>
  <!-- Counter -->
  <script type="text/javascript" src="{% static 'translation/assets/js/waypoints.js' %}"></script>
  <script type="text/javascript" src="{% static 'translation/assets/js/jquery.counterup.js' %}"></script>
  <!-- mixit slider -->
  <script type="text/javascript" src="{% static 'translation/assets/js/jquery.mixitup.js' %}"></script>
  <!-- Add fancyBox -->
  <script type="text/javascript" src="{% static 'translation/assets/js/jquery.fancybox.pack.js' %}"></script>
  <!-- Wow animation -->

  <script type="text/javascript" src="{% static 'translation/assets/js/wow.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <!-- Custom js -->
  <script type="text/javascript" src="{% static 'translation/assets/js/custom.js' %}"></script>


  <script>
    $('.popup').click(function () {
      var src = $(this).attr('src');
      $('.modal').modal('show');
      $('#popup-img').attr('src', src);
    });
  </script>

  <script>
    $(document).ready(function () {
      $("#btn_clone").click(function () {
        $("#cr").clone().appendTo("#cr-clone");
      });
    });
  </script>
  <script>
    $(function () {
      $("#myElem").hide();
      $("#error").hide();
      $("#frm_srt").submit(function () {
        var data = new FormData($('#frm_srt').get(0));
        $.ajax({
          type: "POST",
          url: "{% url 'translation:creat-script' %}",
          data: data,
          cache: false,
          contentType: false,
          processData: false,
          success: function (json) {
            if (json.message == 'ok') {
              $("#error").hide();
              $("#myElem").show();
              $("#watch_but").show();
            }
            else if (json.message == 'not valid') {
              $("#error").show();
              $("#myElem").hide();
            }


          },
          failure: function () {
            $(this).addClass("error");
          }
        });
        return false;
      });
    });
  </script>

</body>

</html>

pfe/translation/templates/translation/generer_script.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Rex : Upload Videos</title>

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/icon" href="{% static 'translation/assets/images/favicon.ico' %}" />
  <!-- Font Awesome -->
  <link href="{% static 'translation/assets/css/font-awesome.css' %}" rel="stylesheet">
  <!-- Sweet Alerte -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css" rel="stylesheet">
  <!-- Bootstrap -->
  <link href="{% static 'translation/assets/css/bootstrap.css' %}" rel="stylesheet">
  <!-- Slick slider -->
  <link rel="stylesheet" type="text/css" href="{% static 'translation/assets/css/slick.css' %}" />
  <!-- Fancybox slider -->
  <link rel="stylesheet" href="{% static 'translation/assets/css/jquery.fancybox.css' %}" type="text/css"
    media="screen" />
  <!-- Animate css -->
  <link rel="stylesheet" type="text/css" href="{% static 'translation/assets/css/animate.css' %}" />
  <!-- Theme color -->
  <link id="switcher" href="{% static 'translation/assets/css/theme-color/default.css' %}" rel="stylesheet">

  <!-- Main Style -->
  <link href="{% static 'translation/style.css' %}" rel="stylesheet">

  <!-- Fonts -->
  <!-- Open Sans for body font -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <!-- Raleway for Title -->
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <!-- Pacifico for 404 page   -->
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
  {% block content %}
  <!-- BEGAIN PRELOADER -->
  <div id="preloader">
    <div class="loader">&nbsp;</div>
  </div>
  <!-- END PRELOADER -->

  <!-- SCROLL TOP BUTTON -->
  <a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->

  <!-- Start menu section -->
  <section id="menu-area">
    <nav class="navbar navbar-default main-navbar" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->
          <a class="navbar-brand logo" href="{% url 'translation:index' %}"><img
              src="{% static 'translation/assets/images/logo.jpg' %}" alt="logo"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav main-nav menu-scroll">
            <li><a href="">Home</a></li>
            <li class="active"><a href="">Import script </a></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
        <div class="search-area">
          <form action="">
            <input id="search" name="search" type="text" placeholder="What're you looking for ?">
            <input id="search_submit" value="Rechercher" type="submit">
          </form>
        </div>
      </div>
    </nav>
  </section>
  <!-- End menu section -->
  <!-- Start blog banner section -->
  <section id="blog-banner">
    <img src="{% static 'translation/assets/images/blog-banner.jpg' %}" alt="img">
    <div class="blog-overlay">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="blog-banner-area">
              <h2>Let's import your script </h2>
              <ol class="breadcrumb">
                <li><a href="{% url 'translation:index' %}">Home</a></li>
                <li class="active">Import scripte</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End blog banner section -->

  <!-- Start blog section -->
  <section id="blog">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="blog-area">
            <div class="row">
              <div class="col-lg-8 col-md-7 col-sm-12">
                <div class="blog-left blog-details">
                  <!-- Start single blog post -->
                  <article class="single-from-blog">

                    <div class="single-widget">
                      <h2>Import script from your computer</h2><br>
                      <form method="POST" action="" id="frm_upload" enctype="multipart/form-data">
                        <input type="file" name="mySub" accept=".vtt,.srt">
                        <video hidden aria-placeholder="Preview" id="video" controls width="450" height="300">
                          <source id="source">
                        </video><br>

                    </div>
                    <center>
                      <p id="Down" class="label label-info " style="display:none">Downloading, please wait ...</p>
                      <p id="myElem" class="label label-success" style="display:none">Subtitle Downloaded , You will be
                        redirected after 3 seconds...</p>
                    </center><br><br>
                    <button class="button button-default col-md-6" data-text="Upload" type="submit" id="upload-btn"
                      name="Upload"><span>Upload</span></button>

                    </form>
                  </article>



                  {% endblock %}

                  <!-- End single blog post -->
                </div>

              </div>

              <div class="col-lg-4 col-md-5 col-sm-12">
                <aside class="blog-right">
                  <!-- Start Sidebar Single widget -->
                  <div class="single-widget">
                    <h2>video Preview</h2>
                    <video controls="" id="media" controls width="300" height="200">
                      <source src="/media/{{video}}">
                    </video>
                  </div>
                  <!-- End Sidebar Single widget -->


                </aside>
              </div>

            </div>


          </div>
        </div>
      </div>
  </section>
  <!-- End blog section -->

  <!-- Start Footer -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer-top-area">
              <a class="footer-logo" href="#"><img src="{% static 'translation/assets/images/logo.jpg' %}"
                  alt="Logo"></a>
              <div class="footer-social">
                <a class="facebook" href="#"><span class="fa fa-facebook"></span></a>
                <a class="twitter" href="#"><span class="fa fa-twitter"></span></a>
                <a class="google-plus" href="#"><span class="fa fa-google-plus"></span></a>
                <a class="youtube" href="#"><span class="fa fa-youtube"></span></a>
                <a class="linkedin" href="#"><span class="fa fa-linkedin"></span></a>
                <a class="dribbble" href="#"><span class="fa fa-dribbble"></span></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </footer>
  <!-- End Footer -->
  <!-- jQuery library -->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <!-- Bootstrap -->

  <script src="{% static 'translation/assets/js/bootstrap.js' %}"></script>
  <!-- Slick Slider -->
  <script type="text/javascript" src="{% static 'translation/assets/js/slick.js' %}"></script>
  <!-- Counter -->
  <script type="text/javascript" src="{% static 'translation/assets/js/waypoints.js' %}"></script>
  <script type="text/javascript" src="{% static 'translation/assets/js/jquery.counterup.js' %}"></script>
  <!-- mixit slider -->
  <script type="text/javascript" src="{% static 'translation/assets/js/jquery.mixitup.js' %}"></script>
  <!-- Add fancyBox -->
  <script type="text/javascript" src="{% static 'translation/assets/js/jquery.fancybox.pack.js' %}"></script>
  <!-- Wow animation -->

  <script type="text/javascript" src="{% static 'translation/assets/js/wow.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <!-- Custom js -->
  <script type="text/javascript" src="{% static 'translation/assets/js/custom.js' %}"></script>

  <script>
    $(function () {
      $("#frm_upload").submit(function () {
        var data = new FormData($('#frm_upload').get(0));
        $("#Down").show();
        $("#myElem").hide();
        $.ajax({
          type: "POST",
          url: "{% url 'translation:generate-script' %}",
          data: data,
          cache: false,
          contentType: false,
          processData: false,
          success: function (json) {
            if (json.message == 'ok') {
              $("#myElem").show();
              $("#Down").hide();
              window.setTimeout(function () {
                window.location.href = "{% url 'translation:watch' %}";
              }, 3000);

            } else if (json.message == "empty") {

            } else if (json.message == "not valid") {

            }


          },
          failure: function () {
            $(this).addClass("error");
          }
        });
        return false;
      });
    });
  </script>
</body>

</html>